// This file is generated by protocol/generate_protocol.mjs. Do not edit.

pub const KIND: &str = "audio";
pub const VERSION: u32 = 1;
pub const SAMPLE_FORMAT: &str = "pcm_s16le";
pub const CHANNELS: u8 = 2;
pub const ENCODING: &str = "base64";
