// This file is generated by protocol/generate_protocol.mjs. Do not edit.

pub const GAMES: &str = "games";
pub const GET_GAMES: &str = "getGames";
pub const GAME_INFO: &str = "gameInfo";
pub const UPDATE_PLAYER_COUNT: &str = "updatePlayerCount";
pub const INIT_WEBRTC: &str = "initwebrtc";
pub const OFFER: &str = "offer";
pub const ANSWER: &str = "answer";
pub const CANDIDATE: &str = "candidate";
pub const JOIN_ROOM: &str = "joinRoom";
pub const TERMINATE_SESSION: &str = "terminateSession";
pub const INPUT: &str = "input";
pub const CONTROLLER_HOST: &str = "controllerHost";
pub const CONTROLLER_READY: &str = "controllerReady";
pub const CONTROLLER_JOIN: &str = "controllerJoin";
pub const CONTROLLER_JOINED: &str = "controllerJoined";
pub const CONTROLLER_LEFT: &str = "controllerLeft";
pub const CONTROLLER_REJECTED: &str = "controllerRejected";
pub const CONTROLLER_INPUT: &str = "controllerInput";
pub const CONTROLLER_AUDIO: &str = "controllerAudio";
