import fs from "node:fs";
import path from "node:path";
import url from "node:url";

const SCRIPT_PATH = url.fileURLToPath(import.meta.url);
const SCRIPT_DIR = path.dirname(SCRIPT_PATH);
const REPO_ROOT = path.resolve(SCRIPT_DIR, "..");

const readJsonFile = (filePath) => JSON.parse(fs.readFileSync(filePath, "utf8"));

const formatGeneratedHeader = (sourcePath) =>
  `// This file is generated by ${sourcePath}. Do not edit.\n`;

const formatGeneratedRustHeader = (sourcePath) =>
  `// This file is generated by ${sourcePath}. Do not edit.\n\n`;

const writeFileIfChanged = (filePath, content) => {
  const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : null;
  if (existing === content) {
    return false;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, "utf8");
  return true;
};

const assertPlainObject = (value, label) => {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`${label} must be an object`);
  }
};

const assertNumber = (value, label) => {
  if (!Number.isFinite(value)) {
    throw new Error(`${label} must be a number`);
  }
};

const assertString = (value, label) => {
  if (typeof value !== "string" || !value) {
    throw new Error(`${label} must be a non-empty string`);
  }
};

const formatJsFrozenObject = (name, entries) => {
  const lines = entries.map(([key, value]) => `  ${key}: ${JSON.stringify(value)},`);
  return `export const ${name} = Object.freeze({\n${lines.join("\n")}\n});\n`;
};

const formatRustStringConsts = (entries) =>
  `${entries.map(([key, value]) => `pub const ${key}: &str = ${JSON.stringify(value)};`).join("\n")}\n`;

const formatRustAudioSpecConsts = (specEntries) => {
  const lines = [];
  for (const [key, value] of specEntries) {
    if (typeof value === "string") {
      lines.push(`pub const ${key}: &str = ${JSON.stringify(value)};`);
      continue;
    }
    if (Number.isFinite(value)) {
      const rustType =
        key === "VERSION" ? "u32" : key === "CHANNELS" ? "u8" : "u32";
      lines.push(`pub const ${key}: ${rustType} = ${value};`);
      continue;
    }
    throw new Error(`Unsupported audio spec value for ${key}`);
  }
  return `${lines.join("\n")}\n`;
};

const main = () => {
  const protocolPath = path.join(SCRIPT_DIR, "arcade_protocol.json");
  const protocol = readJsonFile(protocolPath);

  assertPlainObject(protocol.signalingMessageIds, "signalingMessageIds");
  assertPlainObject(protocol.rtcDataChannelLabels, "rtcDataChannelLabels");
  assertPlainObject(protocol.gameAudioPacketSpec, "gameAudioPacketSpec");
  assertString(protocol.gameAudioPacketSpec.KIND, "gameAudioPacketSpec.KIND");
  assertNumber(protocol.gameAudioPacketSpec.VERSION, "gameAudioPacketSpec.VERSION");
  assertString(
    protocol.gameAudioPacketSpec.SAMPLE_FORMAT,
    "gameAudioPacketSpec.SAMPLE_FORMAT"
  );
  assertNumber(
    protocol.gameAudioPacketSpec.CHANNELS,
    "gameAudioPacketSpec.CHANNELS"
  );
  assertString(
    protocol.gameAudioPacketSpec.ENCODING,
    "gameAudioPacketSpec.ENCODING"
  );

  const sourceRelPath = path.relative(REPO_ROOT, SCRIPT_PATH).replaceAll(path.sep, "/");
  const signalingEntries = Object.entries(protocol.signalingMessageIds);
  const rtcEntries = Object.entries(protocol.rtcDataChannelLabels);
  const audioSpecEntries = Object.entries(protocol.gameAudioPacketSpec);

  const rustIdsPath = path.join(
    REPO_ROOT,
    "arcade-signal-protocol",
    "src",
    "ids.rs"
  );
  const rustRtcPath = path.join(
    REPO_ROOT,
    "arcade-signal-protocol",
    "src",
    "rtc.rs"
  );
  const portalIdsPath = path.join(
    REPO_ROOT,
    "arcade-portal",
    "src",
    "store",
    "generatedMessageIds.js"
  );
  const portalRtcPath = path.join(
    REPO_ROOT,
    "arcade-portal",
    "src",
    "hooks",
    "webrtc",
    "generatedRtcLabels.js"
  );
  const rustAudioSpecPath = path.join(
    REPO_ROOT,
    "arcade-signal-protocol",
    "src",
    "audio.rs"
  );
  const portalAudioSpecPath = path.join(
    REPO_ROOT,
    "arcade-portal",
    "src",
    "hooks",
    "webrtc",
    "generatedGameAudioPacketSpec.js"
  );

  const rustIds = `${formatGeneratedRustHeader(sourceRelPath)}${formatRustStringConsts(signalingEntries)}`;
  const rustRtc = `${formatGeneratedRustHeader(sourceRelPath)}${formatRustStringConsts(rtcEntries)}`;
  const rustAudioSpec = `${formatGeneratedRustHeader(sourceRelPath)}${formatRustAudioSpecConsts(audioSpecEntries)}`;

  const portalIds = `${formatGeneratedHeader(sourceRelPath)}\n${formatJsFrozenObject(
    "SIGNALING_MESSAGE_IDS",
    signalingEntries
  )}`;
  const portalRtc = `${formatGeneratedHeader(sourceRelPath)}\n${formatJsFrozenObject(
    "RTC_DATA_CHANNEL_LABELS",
    rtcEntries
  )}`;
  const portalAudioSpec = `${formatGeneratedHeader(sourceRelPath)}\n${formatJsFrozenObject(
    "GAME_AUDIO_PACKET_SPEC",
    audioSpecEntries
  )}`;

  const changed = [
    writeFileIfChanged(rustIdsPath, rustIds),
    writeFileIfChanged(rustRtcPath, rustRtc),
    writeFileIfChanged(rustAudioSpecPath, rustAudioSpec),
    writeFileIfChanged(portalIdsPath, portalIds),
    writeFileIfChanged(portalRtcPath, portalRtc),
    writeFileIfChanged(portalAudioSpecPath, portalAudioSpec),
  ];

  const wroteAny = changed.some(Boolean);
  const status = wroteAny ? "updated" : "no changes";
  process.stdout.write(`protocol generation: ${status}\n`);
};

main();
