// This file is generated by protocol/generate_protocol.mjs. Do not edit.

export const GAME_AUDIO_PACKET_SPEC = Object.freeze({
  KIND: "audio",
  VERSION: 1,
  SAMPLE_FORMAT: "pcm_s16le",
  CHANNELS: 2,
  ENCODING: "base64",
});
