// This file is generated by protocol/generate_protocol.mjs. Do not edit.

export const SIGNALING_MESSAGE_IDS = Object.freeze({
  GAMES: "games",
  GET_GAMES: "getGames",
  GAME_INFO: "gameInfo",
  UPDATE_PLAYER_COUNT: "updatePlayerCount",
  INIT_WEBRTC: "initwebrtc",
  OFFER: "offer",
  ANSWER: "answer",
  CANDIDATE: "candidate",
  JOIN_ROOM: "joinRoom",
  TERMINATE_SESSION: "terminateSession",
  INPUT: "input",
  CONTROLLER_HOST: "controllerHost",
  CONTROLLER_READY: "controllerReady",
  CONTROLLER_JOIN: "controllerJoin",
  CONTROLLER_JOINED: "controllerJoined",
  CONTROLLER_LEFT: "controllerLeft",
  CONTROLLER_REJECTED: "controllerRejected",
  CONTROLLER_INPUT: "controllerInput",
  CONTROLLER_AUDIO: "controllerAudio",
});
